import sys
import subprocess

day = sys.argv[1] # an number representing day 1 - 5

# run 3 sessions of the front-end
for i in range(1,4):
    # read in the commands for the session
    commands = open('io/commands/day_'+str(day)+"/"+str(i)+".txt")
    # open the front-end as subprocess and pip the commands in as input
    front_process = subprocess.Popen(['python', 'front/front.py', 'io/vsl/'+ day + ".txt", 'io/tsf/day_'+day+'/'+str(i)+'.txt'], stdin=commands)
    front_process.wait()
    commands.close()

# open the mtsf
mtsf = open('io/mtsf/'+ day +'.txt', "w")

# use the three tsfs generated by the 3 front-end sessions to create the mtsf
for i in range(1,4):
    tsf = open('io/tsf/day_'+day+'/'+str(i)+'.txt', "r")
    for line in tsf:
        if not "EOS" in line:
            mtsf.write(line)

mtsf.write("EOS 00000 0 00000 **** 0")
mtsf.close()

# run the backend and create the output files for the next day (day + 1) 
# that will be used for input on the next day
back_process = subprocess.Popen(
    [
        'python', 'back/back.py', 
        'io/csf/'+ day + ".txt", 
        'io/mtsf/'+ day + ".txt", 
        'io/csf/'+ str(int(day) + 1) + ".txt", 
        'io/vsl/'+ str(int(day) + 1) + ".txt", 
    ]
)

back_process.wait()
